### ISSUE TITLE
Auto-saving causes issues with File Watchers plugin

### ISSUE THREAD

**Issue by Feuermurmel** [szabope/mypy-pycharm-plugin#36]
I did another test-drive of the plugin. I'm currently using [mypy-pycharm](https://github.com/leinardi/mypy-pycharm).

I noticed that when the plugin is enabled, Python files get saved automatically within a second when edited. This causes an issue with the [File Watchers](https://www.jetbrains.com/help/idea/using-file-watchers.html)﻿ plugin, which we are using to trigger external auto-formatters (via [pre-commit](https://pre-commit.com)) on save.

The problem is that the auto-formatter we're using for Python ([black](https://github.com/psf/black)) removes excess empty lines. If I now try to add code by adding a few new lines, these disapper again unless I'm quick with starting to type. There are numorous other situations where running external auto-formatters in the middle of editing code a bit annoying, but this example with empty lines makes is near-impossible to work.

Here is a screen recording of showing the behavior:

https://github.com/user-attachments/assets/9563141d-eb5c-4ffa-9231-b3cbd3afb64d

The File Watchers plugin settings we're using:

![Screenshot 2024-12-29 at 14 11 00](https://github.com/user-attachments/assets/787aa601-7ed1-4f06-84f2-280fd57350bb)

![Screenshot 2024-12-29 at 14 11 06](https://github.com/user-attachments/assets/da05e34b-f9cd-4890-95f1-661ef14dff41)

`.pre-commit-config.yaml`:

```yaml
minimum_pre_commit_version: 3.2.0
default_install_hook_types: [pre-commit]

repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        stages: [pre-commit, manual]
```
