### ISSUE TITLE
Support reading mypy configuration from pyproject.toml

### ISSUE THREAD

**Issue by Nagato-Yuzuru** [szabope/mypy-pycharm-plugin#76]
The mypy PyCharm plugin does not read configuration from pyproject.toml. 

This change aligns with [PEP 518](https://peps.python.org/pep-0518/), which defines pyproject.toml as a central configuration file for Python projects. [Mypy](https://github.com/python/mypy/issues/5205) already use this file for their configuration. It would be useful to support loading mypy settings from this file.

**Comment by Nagato-Yuzuru** [comment]
> I have a pyproject.toml:

Thank you for your work on the plugin. In my case, the exclude setting is not applied correctly.

- plugin version: 1.0.16
- mypy section see below
- not space in path

![Image](https://github.com/user-attachments/assets/aca79867-8909-43dc-9bff-e403ed431d0d)

Reproduction Steps:

Exist files: pyproject.toml, other py file and t.py.

In pyproject.toml, add the following configuration: 
```toml
[tool.mypy]
strict = false
warn_return_any = true
warn_unused_ignores = true
```


In t.py, add the following code: 
```python
def f(s: str):
    pass

f(1)
```

Run `mypy .` in the terminal. It correctly reports an error

![Image](https://github.com/user-attachments/assets/a33e991d-b489-47f0-a85c-70ede8986a1b)

In PyCharm, the error is also

![Image](https://github.com/user-attachments/assets/0e6cc9e4-85dc-4ee7-b6ad-c9afe65aa5d6)

Add the exclude comment.

```toml
[tool.mypy]
strict = false
warn_return_any = true
warn_unused_ignores = true
exclude = [
    "t\\.py$"
]
```

Run `mypy .` again

![Image](https://github.com/user-attachments/assets/602e38cc-e262-4edb-a141-1cb5fe9c9b81)

PyCharm still gives an error

![Image](https://github.com/user-attachments/assets/dd107f32-42fc-4aeb-92da-0ad660f7aa20)

![Image](https://github.com/user-attachments/assets/3cfa1c63-9aa4-49ff-962c-72796fe6c815)
